server:
 port: 9091

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    open-in-view: true

  datasource:
    url: jdbc:mysql://192.168.219.128:3306/mydb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    #url: jdbc:mysql://localhost:3306/mydb
    password: 123456a
    username: root
    driverClassName: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
# datasource:
#  url: jdbc:mysql://192.168.191.128:3306/mydb?characterEncoding=UTF-8
#  username: root
#  password: 123456a
#  driverClassName: com.mysql.jdbc.Driver

